apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    appVersion: {{ .Chart.AppVersion }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  default.conf: |-
    proxy_cache_path /opt/joomla_cache levels=1:2 
      keys_zone=joomla_cache:10m max_size=100m inactive=60m 
      use_temp_path=off;

    server {
        listen       8080;
        server_name  localhost;

        location / {
            proxy_set_header HOST $host:$server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1;
        }

        location ~ \.(css|gif|ico|jpe?g|js|png)$ {
            proxy_cache joomla_cache;
            proxy_cache_methods GET;
            proxy_cache_min_uses 3;
            proxy_set_header HOST $host:$server_port;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://127.0.0.1;
        }

    }