kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    appVersion: {{ .Chart.AppVersion }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Chart.Version }}
      appVersion: {{ .Chart.AppVersion }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Chart.Version }}
        appVersion: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          ports:
            - name: http8080
              containerPort: 8080
        - name: joomla
          image: {{ .Values.image.demoJoomla.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          env:
          - name: JOOMLA_DB_HOST
            value: joomla-db-mariadb:3306
          - name: JOOMLA_DB_USER
            value: root
          - name: JOOMLA_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: mariadb-root-password
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
          - name: var-www-html
            mountPath: /var/www/html
      volumes:
      - name: var-www-html
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: nginx-conf
        configMap:
          name: {{ .Release.Name }}-nginx
          items:
          - key: default.conf
            path: default.conf