apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    appVersion: {{ .Chart.AppVersion }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

data:
  mariadb-root-password: {{ default "" .Values.mariadb.password | b64enc | quote }}